# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
aliases:
  - &save-cache-maven
          paths:
            - ~/.m2
          key: v1-dependencies-maven {{ checksum "workspace/repo/<< parameters.module_name >>/pom.xml" }}
attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/working-dir/workspace
executors:
  java_executor:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/working-dir

    environment:
      MAVEN_OPTS: -Xmx3200m
commands:
   save_all_cache:
      description: "A command that saves all caches"
      steps:
           - save_cache: *save-cache-maven
   persist_maven:
      steps:
           - persist_to_workspace:
              root: ~/
              paths:
                - .m2
   restore_maven:
      steps:
           - run: |
                mkdir -p ~/.m2/ 
                cp -r workspace/.m2 ~/.m2 2>/dev/null || true
   maven_cmd:
      description: "A command that executes mvn dependency:go-offline"
      parameters:
          module_name:
              type: string
          cmd:
              type: string
              default: dependency:go-offline
          key:
              type: string
              default: ""
      steps:
          - *attach_workspace
          - run: |
               ([ -z "<< parameters.key >>"] && cat "workspace/repo/<< parameters.module_name >>/pom.xml" || cat "workspace/repo/<< parameters.key >>") > workspace/repo/key.tmp
          - restore_cache: 
               keys:
                   - v1-dependencies-maven {{ checksum "workspace/repo/key.tmp" }}
          - run: | 
               cd workspace/repo/<< parameters.module_name >>
               mvn << parameters.cmd >>
          - save_cache:
               paths:
                   - ~/.m2
               key: v1-dependencies-maven {{ checksum "workspace/repo/<< parameters.module_name >>/pom.xml" }}
          - run: |
               cd workspace/repo/<< parameters.module_name >>
               mvn integration-test
jobs:
  checkout_code:
     executor: java_executor
     steps:
         - checkout:
              path: workspace/repo
         - persist_to_workspace:
              root: workspace
              paths:
                - repo
  build_exercise02_1:
    executor: java_executor
    steps:
      - maven_cmd:
          module_name: "exercise02_1"
  build_exercise02_2:
    executor: java_executor
    steps:
      - maven_cmd:
          module_name: "exercise02_2"
  build_exercise03_1:
    executor: java_executor
    steps:
      - maven_cmd:
          module_name: "exercise03_1"
  build_exercise03_2:
    executor: java_executor
    steps:
      - maven_cmd:
          module_name: "exercise03_2"
  build_exercise04_1:
    executor: java_executor
    steps:
      - maven_cmd:
          module_name: "exercise04_1"
  build_exercise05_1:
    executor: java_executor
    steps:
      - maven_cmd:
          module_name: "exercise05_1"
  build_exercise06_1:
    executor: java_executor
    steps:
      - maven_cmd:
          module_name: "exercise06_1"
  build_exercise07_1:
    executor: java_executor
    steps:
      - maven_cmd:
          module_name: "exercise07_1"
  build_exercise11_1:
    executor: java_executor
    steps:
      - maven_cmd:
          module_name: "exercise11_1"
  build_exercise11_2:
    executor: java_executor
    steps:
      - maven_cmd:
          module_name: "exercise11_2"
  build_exercise11_3:
    executor: java_executor
    steps:
      - maven_cmd:
          module_name: "exercise11_3"
  build_exercise12_1:
    executor: java_executor
    steps:
      - maven_cmd:
          module_name: "exercise12_1"
  build_exercise12_2:
    executor: java_executor
    steps:
      - maven_cmd:
          module_name: "exercise12_2"
  build_exercise13_1:
    executor: java_executor
    steps:
      - maven_cmd:
          module_name: "exercise13_1"
  build_exercise13_2:
    executor: java_executor
    steps:
      - maven_cmd:
          module_name: "exercise13_2"
  build_exercise15_1:
    executor: java_executor
    steps:
      - maven_cmd:
          module_name: "exercise15_1"
  build_exercise15_2:
    executor: java_executor
    steps:
      - maven_cmd:
          module_name: "exercise15_2"
  build_exercise16_1:
    executor: java_executor
    steps:
      - maven_cmd:
          module_name: "exercise16_1"
  build_exercise16_2:
    executor: java_executor
    steps:
      - maven_cmd:
          module_name: "exercise16_2"
  build_exercise17_1:
    executor: java_executor
    steps:
      - maven_cmd:
          module_name: "exercise17_1"
  build_exercise17_2:
    executor: java_executor
    steps:
      - maven_cmd:
          module_name: "exercise17_2"
  build_exercise19_1:
    executor: java_executor
    steps:
      - maven_cmd:
          module_name: "exercise19_1"
  build_exercise20_1:
    executor: java_executor
    steps:
      - maven_cmd:
          module_name: "exercise20_1"
  build_exercise22_1:
    executor: java_executor
    steps:
      - maven_cmd:
          module_name: "exercise22_1"
  build_exercise23_1_client:
    executor: java_executor
    steps:
      - maven_cmd:
          module_name: "exercise23_1/exercise23_1-client"
          key: "exercise23_1/exercise23_1-server/pom.xml"
  build_exercise23_1_server:
    executor: java_executor
    steps:
      - maven_cmd:
          module_name: "exercise23_1/exercise23_1-server"
          cmd: clean install
workflows:
      version: 2
      main:
          jobs:
            - checkout_code
#            - build_exercise02_1:
#                requires:
#                   - checkout_code
#            - build_exercise02_2:
#                requires:
#                   - checkout_code
#            - build_exercise03_1:
#                requires:
#                   - checkout_code
#            - build_exercise03_2:
#                requires:
#                   - checkout_code
#            - build_exercise04_1:
#                requires:
#                   - checkout_code
#            - build_exercise05_1:
#                requires:
#                   - checkout_code
#            - build_exercise06_1:
#                requires:
#                   - checkout_code
#            - build_exercise07_1:
#                requires:
#                   - checkout_code
#            - build_exercise11_1:
#                requires:
#                   - checkout_code
#            - build_exercise11_2:
#                requires:
#                   - checkout_code
#            - build_exercise11_3:
#                requires:
#                   - checkout_code
#            - build_exercise12_1:
#                requires:
#                   - checkout_code
#            - build_exercise12_2:
#                requires:
#                   - checkout_code
#            - build_exercise13_1:
#                requires:
#                   - checkout_code
#            - build_exercise13_2:
#                requires:
#                   - checkout_code
#            - build_exercise15_1:
#                requires:
#                   - checkout_code
#            - build_exercise15_2:
#                requires:
#                   - checkout_code
#            - build_exercise16_1:
#                requires:
#                   - checkout_code
#            - build_exercise16_2:
#                requires:
#                   - checkout_code
#            - build_exercise17_1:
#                requires:
#                   - checkout_code
#            - build_exercise17_2:
#                requires:
#                   - checkout_code
#            - build_exercise19_1:
#                requires:
#                   - checkout_code
#            - build_exercise20_1:
#                requires:
#                   - checkout_code
#            - build_exercise22_1:
#                requires:
#                   - checkout_code
            - build_exercise23_1_client:
                requires:
                   - build_exercise23_1_server				
            - build_exercise23_1_server:
                requires:
                   - checkout_code
