# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build_exercise02_1:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo/exercise02_1

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
  build_exercise02_2:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo/exercise02_2

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
  build_exercise03_1:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo/exercise03_1

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
  build_exercise03_2:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo/exercise03_2

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
  build_exercise04_1:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo/exercise04_1

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
  build_exercise05_1:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo/exercise05_1

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
  build_exercise06_1:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo/exercise06_1

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
  build_exercise07_1:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo/exercise07_1

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
  build_exercise11_1:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo/exercise11_1

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
  build_exercise11_2:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo/exercise11_2

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
  build_exercise11_3:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo/exercise11_3

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
  build_exercise12_1:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo/exercise12_1

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
  build_exercise12_2:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo/exercise12_2

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
  build_exercise13_1:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo/exercise13_1

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
  build_exercise13_2:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo/exercise13_2

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
  build_exercise15_1:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo/exercise15_1

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
  build_exercise15_2:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo/exercise15_2

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
  build_exercise16_1:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo/exercise16_1

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
  build_exercise16_2:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo/exercise16_2

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
  build_exercise17_1:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo/exercise17_1

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
  build_exercise17_2:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo/exercise17_2

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
  build_exercise19_1:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo/exercise19_1

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
  build_exercise20_1:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo/exercise20_1

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
  build_exercise22_1:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo/exercise22_1

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
  build_exercise23_1_client:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo/exercise23_1/exercise23_1-client

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
  build_exercise23_1_server:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo/exercise23_1/exercise23_1-server

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
workflows:
      version: 2
      main:
          jobs:
            - build_exercise02_1
            - build_exercise02_2
            - build_exercise03_1
            - build_exercise03_2
            - build_exercise04_1
            - build_exercise05_1
            - build_exercise06_1
            - build_exercise07_1
            - build_exercise11_1
            - build_exercise11_2
            - build_exercise11_3
            - build_exercise12_1
            - build_exercise12_2
            - build_exercise13_1
            - build_exercise13_2
            - build_exercise15_1
            - build_exercise15_2
            - build_exercise16_1
            - build_exercise16_2
            - build_exercise17_1
            - build_exercise17_2
            - build_exercise19_1
            - build_exercise20_1
            - build_exercise22_1
            - build_exercise23_1_client:
                requires:
                   - build_exercise23_1_server				
            - build_exercise23_1_server
