# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build_exercise02_1:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo/exercise02_1

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
  build_exercise02_2:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo/exercise02_2

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
workflows:
      version: 2
      main:
          jobs:
            - build_exercise02_1
            - build_exercise02_2
